spring:
  datasource:
    url: jdbc:mysql://gameinfo.csom5jlfxec9.ap-northeast-2.rds.amazonaws.com:3306/gameinfo
    username: admin
    password: OzAMshJ2VJaae7tAdekw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: com.project.gameInfo.config.MysqlCustomDialect
  servlet:
    multipart:
      max-file-size: 50MB


jwt:
  token-validity-in-seconds: 600
  refresh-validity-date: 7

server:
  ssl:
    key-store: gameinfo-keystore.p12
    key-store-type: PKCS12
    key-store-password: gameinfo
    key-alias: gameinfo-keystore
  port: 443


custom:
  resource-path: D:\MyProject\personal_project\Images\GameInfo\
  image-path: /img/**